rdata_js.h: rdata.js
	xxd -i rdata.js > rdata_js.h

result_js.h: result.js
	xxd -i result.js > result_js.h

type_js.h: type.js
	xxd -i type.js > type_js.h

util_js.h: util.js
	xxd -i util.js > util_js.h

.PHONY: all

all: rdata_js.h result_js.h type_js.h util_js.h
